// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "c67e5b30-053e-4793-a47f-7d48c9b99ed3";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onAlarmeChange();
void onArmeChange();

bool alarme;
bool arme;
bool detecteur;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(alarme, READWRITE, ON_CHANGE, onAlarmeChange);
  ArduinoCloud.addProperty(arme, READWRITE, ON_CHANGE, onArmeChange);
  ArduinoCloud.addProperty(detecteur, READ, ON_CHANGE, NULL, 10);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
